Ext.define("MyApp.model.CpghdmxModel", {
    extend: "Ext.app.ViewModel", 
    extend: "Ext.data.Model",
    alias: "viewmodel.CpghdmxModel",
    fields: [
    { name: "id", type: "int" },
    { name: "mxid", type: "int" }, 
    { name: "ghid", type: "int" },
    { name: "ghdh" },
    { name: "mxdh" },
    { name: "cdmc" },
    { name: "cdid", type: "int" }, 
    { name: "cpmc" },
    { name: "cpid", type: "int" }, 
    { name: "bzmc" },
    { name: "bzid", type: "int" }, 
    { name: "kcid", type: "int" },
    { name: "jldw" },
    { name: "xssl", type: "float" }, 
    { name: "xszl", type: "float" },
    { name: "xsdj", type: "float" },
    { name: "xsje", type: "float" },
    { name: "ghsl", type: "float" }, 
    { name: "ghzl", type: "float" },
    { name: "ccsl", type: "float" }, 
    { name: "cczl", type: "float" },
    
    { name: "mccsl", type: "float" },
    { name: "mcczl", type: "float" },
    { name: "ccje", type: "float" },
    { name: "xjje", type: "float" }, 
    { name: "cpgg" },
    { name: "cpph" },
    { name: "sldw" },
    { name: "zldw" }, 
    { name: "sm" }, 
    { name: "zlhs", type: "bool" },
    { name: "sl", type: "float" },
    { name: "zl", type: "float" }
    ]
});